import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Lilita_One } from 'next/font/google';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const lilitaOne = Lilita_One({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-lilita',
});

export const metadata = {
  title: 'Mithila Real Estate',
  description: 'Pioneering Architecture & Engineering',
};
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${lilitaOne.variable}`}>
      <body
        className="font-lalita bg-gradient-to-br from-[#fdfcfb] via-[#e2d1c3] to-[#fdfcfb]"
      >
        {children}
      </body>
    </html>
  );
}
